name: Build Switch App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Switch libraries
        run: |
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --noconfirm switch-sdl2 switch-sdl2_gfx

      - name: Compile Application
        run: |
          make

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Pomodoro-Switch-App
          path: pomodoro.nro
